/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watertankproject;

/**
 *
 * @author dinushi
 */
public class AlarmWindow extends javax.swing.JFrame implements WaterLevelObserver{

    /**
     * Creates new form AlarmWindow
     */
    public AlarmWindow() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(144, 166, 167));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlarmStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alarm Window");

        lblAlarmStatus.setBackground(new java.awt.Color(137, 152, 211));
        lblAlarmStatus.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblAlarmStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblAlarmStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlarmStatus.setText("Alarm : ");
        lblAlarmStatus.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblAlarmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblAlarmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAlarmStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int waterLevel) {
        lblAlarmStatus.setText("Alarm : " + (waterLevel > 50 ? "ON" : "OFF"));
    }
}
