/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watertankproject;

/**
 *
 * @author dinushi
 */
public class DisplayWindow extends javax.swing.JFrame implements WaterLevelObservable{

    /**
     * Creates new form DisplayWindow
     */
    public DisplayWindow() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(178, 215, 162));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWaterLevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Display Window");

        lblWaterLevel.setBackground(new java.awt.Color(137, 152, 211));
        lblWaterLevel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblWaterLevel.setForeground(new java.awt.Color(0, 0, 0));
        lblWaterLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWaterLevel.setText("Water Level :");
        lblWaterLevel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblWaterLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(lblWaterLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblWaterLevel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int waterLevel) {
        lblWaterLevel.setText("Water Level : "+waterLevel);
    }
}
