/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watertankproject;

/**
 *
 * @author dinushi
 */
public class SMSSenderWindow extends javax.swing.JFrame implements WaterLevelObservable{

    /**
     * Creates new form SMSSender
     */
    public SMSSenderWindow() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(190, 177, 177));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSMS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Message Window");

        lblSMS.setBackground(new java.awt.Color(137, 152, 211));
        lblSMS.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblSMS.setForeground(new java.awt.Color(0, 0, 0));
        lblSMS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSMS.setText("Sending SMS....");
        lblSMS.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblSMS, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblSMS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSMS;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int waterLevel) {
        lblSMS.setText("Sending SMS..."+waterLevel);
    }
}
