/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watertankproject;

/**
 *
 * @author dinushi
 */
public class SplitterWindow extends javax.swing.JFrame implements WaterLevelObservable{

    /**
     * Creates new form SplitterWindow
     */
    public SplitterWindow() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(224, 221, 171));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSplitter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Splitter Window");

        lblSplitter.setBackground(new java.awt.Color(137, 152, 211));
        lblSplitter.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblSplitter.setForeground(new java.awt.Color(0, 0, 0));
        lblSplitter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSplitter.setText("Splitter : ");
        lblSplitter.setMaximumSize(new java.awt.Dimension(162, 47));
        lblSplitter.setMinimumSize(new java.awt.Dimension(162, 47));
        lblSplitter.setOpaque(true);
        lblSplitter.setPreferredSize(new java.awt.Dimension(162, 47));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblSplitter, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(lblSplitter, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSplitter;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int waterLevel) {
        lblSplitter.setText("Splitter : " + (waterLevel >= 75 ? "ON" : "OFF"));
    }
}
