/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watertankproject;

import java.awt.Color;

/**
 *
 * @author dinushi
 */
public class WaterTank extends javax.swing.JFrame {
    
    private WaterLevelObservableInterface waterLevelObservableInterface;
    
    /**
     * Creates new form WaterTank
     * @param waterLevelObservableInterface
     */
    public WaterTank() {
        initComponents();
        getContentPane().setBackground(new Color(158, 205, 214));        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waterLevelSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Water Tank Window");

        waterLevelSlider.setBackground(new java.awt.Color(158, 205, 214));
        waterLevelSlider.setForeground(new java.awt.Color(0, 0, 0));
        waterLevelSlider.setMajorTickSpacing(10);
        waterLevelSlider.setMinorTickSpacing(1);
        waterLevelSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        waterLevelSlider.setPaintLabels(true);
        waterLevelSlider.setPaintTicks(true);
        waterLevelSlider.setOpaque(true);
        waterLevelSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                waterLevelSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(waterLevelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(waterLevelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waterLevelSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_waterLevelSliderStateChanged
        waterLevelObservableInterface.setWaterLevel(waterLevelSlider.getValue());
    }//GEN-LAST:event_waterLevelSliderStateChanged

    public void addWaterLevelObservable(WaterLevelObservableInterface waterLevelObservableInterface){
        this.waterLevelObservableInterface = waterLevelObservableInterface;        
        waterLevelObservableInterface.setWaterLevel(waterLevelSlider.getValue());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider waterLevelSlider;
    // End of variables declaration//GEN-END:variables
}
